-- DropForeignKey
ALTER TABLE "Mattress" DROP CONSTRAINT "Mattress_id_fkey";
ALTER TABLE "Pad" DROP CONSTRAINT "Pad_id_fkey";
ALTER TABLE "Pillow" DROP CONSTRAINT "Pillow_id_fkey";
ALTER TABLE "Quilt" DROP CONSTRAINT "Quilt_id_fkey";

-- AddForeignKey
ALTER TABLE "Mattress" ADD CONSTRAINT "Mattress_id_fkey" FOREIGN KEY ("id") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Pad" ADD CONSTRAINT "Pad_id_fkey" FOREIGN KEY ("id") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Pillow" ADD CONSTRAINT "Pillow_id_fkey" FOREIGN KEY ("id") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Quilt" ADD CONSTRAINT "Quilt_id_fkey" FOREIGN KEY ("id") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
