-- AlterTable
ALTER TABLE "Quilt" ADD COLUMN IF NOT EXISTS "descriptionKa" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Quilt" ADD COLUMN IF NOT EXISTS "descriptionEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Quilt" ALTER COLUMN "fabric" SET DEFAULT '';
ALTER TABLE "Quilt" ALTER COLUMN "filling" SET DEFAULT '';
ALTER TABLE "Quilt" ALTER COLUMN "fabricEn" SET DEFAULT '';
ALTER TABLE "Quilt" ALTER COLUMN "fillingEn" SET DEFAULT '';
ALTER TABLE "Quilt" ALTER COLUMN "weight" SET DEFAULT '';
ALTER TABLE "Quilt" ALTER COLUMN "minitext" SET DEFAULT '';
ALTER TABLE "Quilt" ALTER COLUMN "minitextEn" SET DEFAULT '';
