-- AlterTable
ALTER TABLE "Quilt" ADD COLUMN IF NOT EXISTS "packaging" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Quilt" ADD COLUMN IF NOT EXISTS "packagingEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Quilt" ADD COLUMN IF NOT EXISTS "care" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Quilt" ADD COLUMN IF NOT EXISTS "careEn" TEXT NOT NULL DEFAULT '';
